FROM node:20-slim

# Create app directory
WORKDIR /app

# Install dependencies based on package.json & package-lock.json
COPY package*.json ./
RUN npm ci --only=production

# Copy source code
COPY . .

# Set PORT environment variable default
ENV PORT=5000
EXPOSE $PORT

# Start the API server
CMD ["sh", "-c", "node scripts/init-all.js && node server.js"]
