FROM node:20-slim

# Create app directory
WORKDIR /app

# Install dependencies based on package.json & package-lock.json
COPY package*.json ./
RUN npm ci --only=production

# Copy source code
COPY . .

# Start the Worker process
CMD ["node", "worker.js"]
