"use client";

import { useMemo, useState } from "react";

export type OutputTab = "sources" | "report" | "pdf" | "latex";

type Source = {
  title: string;
  url: string;
};

interface ResearchOutputPanelProps {
  activeTab: OutputTab;
  onTabChange: (tab: OutputTab) => void;
  reportContent?: string;
  sources?: Source[];
}

const tabs: { key: OutputTab; label: string }[] = [
  { key: "sources", label: "Sources" },
  { key: "report", label: "Report" },
  { key: "pdf", label: "PDF" },
  { key: "latex", label: "LaTeX" },
];

function SourcesTab({ sources }: { sources: Source[] }) {
  return (
    <div className="space-y-3">
      {sources.length === 0 ? (
        <p className="rounded-2xl border border-[#E5A985]/20 bg-white/[0.03] p-6 text-center text-sm text-white/50">
          No sources yet. Start a research session.
        </p>
      ) : (
        sources.map((source, i) => (
          <div
            key={`${source.url}-${i}`}
            className="w-full rounded-2xl border border-[#E5A985]/20 bg-white/[0.03] p-4 text-left transition-all"
          >
            <p className="mb-2 text-sm font-semibold leading-snug text-white">
              {source.title || `Source ${i + 1}`}
            </p>
            <a
              href={source.url}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1 text-xs text-[#E5A985] underline underline-offset-2 hover:text-[#f2c09f]"
            >
              {source.url}
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                className="h-3 w-3"
              >
                <path d="M7 17L17 7" />
                <path d="M8 7h9v9" />
              </svg>
            </a>
          </div>
        ))
      )}
    </div>
  );
}

function ReportTab({ content }: { content: string }) {
  if (!content) {
    return (
      <div className="rounded-2xl border border-[#E5A985]/20 bg-white/[0.03] p-6 text-center text-sm text-white/50">
        No report yet. Ask a research question to generate one.
      </div>
    );
  }

  const sections = content.split(/(?=^## )/m);

  return (
    <div className="space-y-4 text-sm leading-relaxed text-white/85">
      {sections.map((section, i) => {
        const titleMatch = section.match(/^## (.+)$/m);
        const title = titleMatch ? titleMatch[1] : null;
        const body = title ? section.replace(/^## .+\n/, "").trim() : section.trim();

        if (!body) return null;

        return (
          <section
            key={i}
            className="rounded-2xl border border-[#E5A985]/18 bg-white/[0.03] p-4"
          >
            {title && (
              <h3 className="mb-2 text-sm font-semibold text-[#E5A985]">{title}</h3>
            )}
            <div className="whitespace-pre-wrap text-white/80">
              {body.split(/\n{2,}/).map((paragraph, j) => {
                if (paragraph.startsWith("- ")) {
                  return (
                    <ul key={j} className="list-disc space-y-1 pl-5">
                      {paragraph.split("\n").map((line, k) => (
                        <li key={k}>{line.replace(/^- /, "")}</li>
                      ))}
                    </ul>
                  );
                }
                return <p key={j} className="mb-2">{paragraph}</p>;
              })}
            </div>
          </section>
        );
      })}
    </div>
  );
}

function PdfTab({ reportContent }: { reportContent: string }) {
  const downloadPdf = () => {
    const text = reportContent || "No content";
    const blob = new Blob([text], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "research-report.pdf";
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      <div className="rounded-2xl border border-[#E5A985]/18 bg-white/[0.03] p-4">
        <h3 className="text-sm font-semibold text-[#E5A985]">Research Report</h3>
        <p className="mt-1 text-xs text-white/65">Generated by Multiagent Research Automation Platform</p>
      </div>

      {reportContent ? (
        <div className="rounded-2xl border border-[#E5A985]/20 bg-[#f8f7f4] p-4 text-[#1a1a1a] shadow-inner">
          <p className="text-[10px] uppercase tracking-[0.2em] text-[#8a6a57]">Document Preview</p>
          <div className="mt-4 min-h-[280px] rounded-xl border border-[#d8cfc6] bg-white p-4 shadow-[0_8px_24px_rgba(26,26,26,0.08)]">
            <div className="whitespace-pre-wrap text-xs leading-relaxed">
              {reportContent.slice(0, 1000)}
              {reportContent.length > 1000 && "..."}
            </div>
          </div>
        </div>
      ) : (
        <div className="rounded-2xl border border-[#E5A985]/20 bg-white/[0.03] p-6 text-center text-sm text-white/50">
          No content to export.
        </div>
      )}

      <div className="flex gap-2">
        <button
          type="button"
          onClick={downloadPdf}
          className="rounded-xl border border-[#E5A985]/35 px-3 py-2 text-xs text-[#E5A985] transition hover:bg-[#E5A985]/10"
        >
          Download PDF
        </button>
      </div>
    </div>
  );
}

function LatexTab({ reportContent }: { reportContent: string }) {
  const [copied, setCopied] = useState(false);

  const latexContent = reportContent
    ? `\\documentclass{article}
\\usepackage{hyperref}
\\title{Research Report}
\\author{Multiagent Research Automation Platform}
\\begin{document}
\\maketitle

${reportContent
  .split("\n")
  .map((line) => {
    if (line.startsWith("## ")) return `\\section{${line.slice(3)}}`;
    if (line.startsWith("- ")) return `\\item ${line.slice(2)}`;
    if (line.startsWith("Source: ") || line.startsWith("URL: ")) return `\\paragraph{${line}}`;
    return line;
  })
  .join("\n")}

\\end{document}`
    : "";

  const copyLatex = async () => {
    try {
      await navigator.clipboard.writeText(latexContent);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1400);
    } catch {
      setCopied(false);
    }
  };

  if (!latexContent) {
    return (
      <div className="rounded-2xl border border-[#E5A985]/20 bg-white/[0.03] p-6 text-center text-sm text-white/50">
        No content to export.
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <div className="overflow-hidden rounded-2xl border border-[#E5A985]/20 bg-black/40">
        <pre className="max-h-[420px] overflow-auto p-4 text-xs leading-relaxed text-[#E5A985]/90">
          {latexContent}
        </pre>
      </div>

      <div className="flex gap-2">
        <button
          type="button"
          onClick={copyLatex}
          className="rounded-xl border border-[#E5A985]/35 px-3 py-2 text-xs text-[#E5A985] transition hover:bg-[#E5A985]/10"
        >
          {copied ? "Copied" : "Copy LaTeX"}
        </button>
      </div>
    </div>
  );
}

export default function ResearchOutputPanel({
  activeTab,
  onTabChange,
  reportContent = "",
  sources = [],
}: ResearchOutputPanelProps) {
  const sourceCount = sources.length;

  return (
    <aside
      className="
        min-h-0 w-full min-w-0 rounded-[28px]
        border border-[#E5A985]/20 bg-[#1a1a1a]
        shadow-[0_24px_90px_rgba(26,26,26,0.28)]
        lg:h-full
      "
    >
      <div className="border-b border-[#E5A985]/15 p-5">
        <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
          <h3 className="text-lg font-semibold text-white">Research Workspace</h3>
          {sourceCount > 0 && (
            <span className="rounded-full border border-[#22c55e]/35 bg-[#22c55e]/12 px-2.5 py-1 text-[11px] text-[#86efac]">
              {sourceCount} source{sourceCount !== 1 ? "s" : ""}
            </span>
          )}
        </div>

        <p className="text-xs text-white/65">
          Live sources, structured notes, and export-ready outputs.
        </p>

        <div className="mt-4 flex flex-wrap gap-2">
          {tabs.map((tab) => {
            const active = activeTab === tab.key;
            return (
              <button
                key={tab.key}
                type="button"
                onClick={() => onTabChange(tab.key)}
                className={[
                  "rounded-full px-3 py-1.5 text-xs font-medium transition",
                  active
                    ? "bg-[#E5A985] text-[#1a1a1a]"
                    : "border border-[#E5A985]/20 bg-white/5 text-[#E5A985]/85 hover:bg-[#E5A985]/12",
                ].join(" ")}
              >
                {tab.label}
              </button>
            );
          })}
        </div>
      </div>

      <div className="h-[calc(100%-178px)] min-h-0 overflow-y-auto p-5 lg:max-h-[calc(100vh-300px)]">
        {activeTab === "sources" && <SourcesTab sources={sources} />}
        {activeTab === "report" && <ReportTab content={reportContent} />}
        {activeTab === "pdf" && <PdfTab reportContent={reportContent} />}
        {activeTab === "latex" && <LatexTab reportContent={reportContent} />}
      </div>
    </aside>
  );
}
